SimpleShop/urls.py
from django.contrib import admin
from django.urls import path, include

from shop.views import index, contact, detail, add, delete, edit

urlpatterns = [
    path('', index, name='index'),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('contact/', contact, name='contact'),
    path('product/', include('shop.urls')),
    path('dashboard/', include('dashboard.urls')),
]

shop/urls.py
from django.urls import path

from . import views
from .views import detail, delete, edit, add, CartView, AddToCartView, UpdateCartView, RemoveFromCartView, CheckoutView, \
    OrderConfirmationView, OrderConfirmationView2

app_name = 'shop'


urlpatterns = [
    path('', views.search, name='search'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/', AddToCartView.as_view(), name='add_to_cart'),
    path('cart/update/<int:product_id>/', UpdateCartView.as_view(), name='update_cart'),
    path('cart/remove/<int:product_id>/', RemoveFromCartView.as_view(), name='remove_cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('success/<int:order_id>', OrderConfirmationView.as_view(), name='order_success'),
    path('product/success/', OrderConfirmationView2.as_view(), name='order_success_no_id'),
    path('product/add/', views.add, name='add_product'),
    path('product/<int:pk>/', views.detail, name='detail'),
    path('product/<int:pk>/delete/', views.delete, name='delete'),
    path('product/<int:pk>/edit/', views.edit, name='edit'),
    ]

shop/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=256)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Address(models.Model):
    street = models.CharField(max_length=255)
    street_number = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    country = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.street} {self.street_number}, {self.city}, {self.postal_code}, {self.country}'


class Order(models.Model):
    CART = 1
    PROCESSING = 2
    COMPLETED = 3
    CANCELLED = 4
    STATUS_CHOICES = [
        (CART, 'In Cart'),
        (PROCESSING, 'Being Processed'),
        (COMPLETED, 'Completed'),
        (CANCELLED, 'Cancelled'),
    ]

    PAYMENT_CHOICES = [
        ('CC', 'Credit Card'),
        ('PP', 'PayPal'),
        ('COD', 'Cash on Delivery'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders', null=True, blank=True)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, blank=True)
    payment_method = models.CharField(max_length=3, choices=PAYMENT_CHOICES, default='CC')
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    paid = models.BooleanField(default=False)
    status = models.IntegerField(choices=STATUS_CHOICES, default=CART)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Order {self.id} - {self.name} {self.surname} - {self.get_status_display()}'


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='products')
    product = models.ForeignKey('shop.Product', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} x {self.product.name}'

shop/forms.py
from django import forms

from .models import Product, Address

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'name', 'price', 'description')

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }


class EditProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'name', 'price', 'description', 'is_sold')

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('street', 'street_number', 'postal_code', 'city', 'country')

shop/views.py
from audioop import reverse

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from django.db.models import Q
from django.views import View
from django.views.generic import TemplateView

from .forms import AddProductForm, EditProductForm
from shop.models import Product, Category, OrderProduct, Order, Address


def search(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    products = Product.objects.filter(is_sold=False)

    if category_id:
        products = products.filter(category_id=category_id)

    if query:
        products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'shop/search.html', {
        'products': products,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })


def index(request):
    products = Product.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'shop/index.html', {
        'categories': categories,
        'products': products
    })


def contact(request):
    return render(request, 'shop/contact.html')


def detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    related_products = Product.objects.filter(category=product.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'product/detail.html' ,{
        'product': product,
        'related_products': related_products,
    })


@login_required()
def add(request):
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)

        if form.is_valid():
            product = form.save(commit=False)
            product.created_by = request.user
            product.save()

            return redirect('shop:detail', pk=product.pk)
    else:
        form = AddProductForm()

    return render(request, 'product/add.html' ,{
        'form': form,
        'title': 'Add Product',
    })


@login_required
def edit(request, pk):
    product = get_object_or_404(Product, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditProductForm(request.POST, request.FILES, instance=product)

        if form.is_valid():
            form.save()

            return redirect('shop:detail', pk=product.id)
    else:
        form = EditProductForm(instance=product)

    return render(request, 'product/form.html', {
        'form': form,
        'title': 'Edit item',
    })


@login_required
def delete(request, pk):
    product = get_object_or_404(Product, pk=pk, created_by=request.user)
    product.delete()

    return redirect('dashboard:dashboard')


class CartView(TemplateView):
    template_name = 'shop/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = self.request.session.get('cart', {})
        cart_products = []
        total_price = 0

        for product_id, quantity in cart.items():
            product = get_object_or_404(Product, id=product_id)
            total_product_price = product.price * quantity
            total_price += total_product_price
            cart_products.append({
                'product': product,
                'quantity': quantity,
                'total_product_price': total_product_price,
            })

        context['cart_cart_products'] = cart_products
        context['total_price'] = total_price
        return context


class AddToCartView(View):
    def post(self, request, *args, **kwargs):
        product_id = request.POST.get('product_id')
        product = get_object_or_404(Product, id=product_id)

        try:
            quantity = int(request.POST.get('quantity', 1))
            if quantity <= 0:
                messages.error(request, "Quantity must be greater than zero.")
                return redirect('shop:cart')
        except ValueError:
            messages.error(request, "Invalid quantity. Please provide a valid number.")
            return redirect('shop:cart')

        cart = request.session.get('cart', {})
        cart[product_id] = cart.get(product_id, 0) + quantity
        request.session['cart'] = cart

        messages.success(request, f"{quantity} {product.name}{'s' if quantity > 1 else ''} added to cart.")
        return redirect('shop:cart')


class UpdateCartView(View):
    def post(self, request, product_id):
        submitted_quantity = request.POST.get('quantity', '').strip()
        cart = request.session.get('cart', {})

        current_quantity = cart.get(str(product_id), 1)

        if submitted_quantity.isdigit() and int(submitted_quantity) > 0:
            current_quantity = int(submitted_quantity)
            product = get_object_or_404(Product, id=product_id)

        request.session['cart'] = cart
        request.session.modified = True

        return redirect(reverse('cart'))


class RemoveFromCartView(View):
    def get(self, request, product_id):
        cart = request.session.get('cart', {})

        if str(product_id) in cart:
            del cart[str(product_id)]

        request.session['cart'] = cart
        return redirect(reverse('cart'))


class CheckoutView(View):
    def get(self, request):
        # Calculate total price from session cart
        cart = request.session.get('cart', {})
        total_price = 0
        for product_id, quantity in cart.items():
            product = Product.objects.get(id=product_id)
            total_price += product.price * quantity

        # Pass total price to template
        context = {
            'total_price': total_price,
        }
        return render(request, 'shop/checkout.html', context)

    def post(self, request):
        # Extract form data
        name = request.POST.get('name')
        surname = request.POST.get('surname')
        email = request.POST.get('email')
        phone_number = request.POST.get('number')
        street = request.POST.get('street_name')
        street_number = request.POST.get('street_number')
        city = request.POST.get('city')
        postal_code = request.POST.get('postal_code')
        country = request.POST.get('country')
        payment_method = request.POST.get('payment_method')

        try:
            # First, create an Address instance
            address = Address.objects.create(
                street=street,
                street_number=street_number,
                city=city,
                postal_code=postal_code,
                country=country
            )

            # Then create an Order instance
            order = Order.objects.create(
                user=request.user,
                address=address,
                payment_method=payment_method,
                name=name,
                surname=surname,
                email=email,
                phone_number=phone_number,
                paid=False,
                status=Order.PROCESSING
            )

            # Process cart items from session
            cart = request.session.get('cart', {})
            for product_id, quantity in cart.items():
                product = Product.objects.get(id=product_id)
                OrderProduct.objects.create(
                    order=order,
                    product=product,
                    quantity=quantity
                )

            # Clear the cart from session after processing
            request.session['cart'] = {}

            messages.success(request, "Your order has been placed successfully!")
            return redirect(reverse('order-success', kwargs={'order_id': order.id}))

        except Exception as e:
            messages.error(request, f"There was an error processing your order: {str(e)}")
            return redirect('checkout')


class OrderConfirmationView2(View):
    def get(self, request):
        return render(request, 'shop/order-success.html')


class OrderConfirmationView(View):
    def get(self, request, order_id):
        # Retrieve the order using the order_id
        order = get_object_or_404(Order, id=order_id)
        # Add any additional context you want to pass to the template
        context = {
            'order': order,
        }
        return render(request, 'shop/order-success.html', context)

shop/templates/product/add.html
{% extends 'shop/base.html' %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}

shop/templates/product/detail.html
{% extends 'shop/base.html' %}
{% block title %}{{ product.name }}{% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="col-span-3">
            <img src="{{ product.image.url }}" class="rounded-xl">
        </div>

        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">{{ product.name }}</h1>
            <p class="text-gray-500"><strong>Price: </strong>{{ product.price }}</p>
            <p class="text-gray-500"><strong>Seller: </strong>{{ product.created_by }}</p>

            {% if product.description %}
                <p class="text-gray-700">
                    <strong class="text-gray-500">Description</strong><br>
                    {{ product.description }}
                </p>
            {% endif %}

            {% if request.user == product.created_by %}
                <div class="mt-6 p-6 bg-white rounded-xl">
                    <p>Your product</p>

                    <a href="{% url 'shop:edit' product.id %}"
                       class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                    <a href="{% url 'shop:delete' product.id %}"
                       class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
                </div>
                <form action="{% url 'shop:add_to_cart' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ product.id }}">
                    <input type="number" name="quantity" value="1" min="1">
                    <button type="submit"
                            class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">
                        Add to Cart
                    </button>
                </form>
            {% else %}

                <a href="{% url 'contact' %}"
                   class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact
                    seller</a>
                <form action="{% url 'shop:add_to_cart' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="product_id" value="{{ product.id }}">
                    <input type="number" name="quantity" value="1" min="1">
                    <button type="submit"
                            class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">
                        Add to Cart
                    </button>
                </form>

            {% endif %}
        </div>

    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for product in related_products %}
                <div>
                    <a href="{% url 'shop:detail' product.id %}"></a>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ product.name }}</h2>
                        <p class="text-gray-500">Price: {{ product.price }}</p>
                    </div>
                    </a>
                </div>
            {% endfor %}
{% endblock %}

shop/templates/product/form.html
{% extends 'shop/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}